version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: whatsapp_bot
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin123@postgres:5432/whatsapp_bot
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - ./whatsapp_sessions:/app/whatsapp_sessions
    networks:
      - app-network

  baileys:
    build: ./baileys_service
    ports:
      - "3001:3001"
    environment:
      - SESSION_PATH=/app/sessions
    volumes:
      - ./whatsapp_sessions:/app/sessions
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge